apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  UI_BACKEND_URL: "http://backend:8888"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  CAT_BACKEND_PORT: "8888"
  CAT_BACKEND_HOST: "backend"
  CAT_BACKEND_ALLOWED_ORIGINS: '["*"]'