[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dev_ui"
version = "0.1.0"
description = "Dev UI for NetEase."
readme = "README.md"
requires-python = ">=3.12,<3.13"
authors = [{ name = "AvePoint", email = "avepoint@avepoint.com" }]
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.8.0",
    "streamlit==1.40.1",
]

[tool.hatch.build.targets.wheel]
packages = ["src/dev_ui"]
