services:
  netease:
    build:
      context: ../..
      dockerfile: ./docker/net.dockerfile
    container_name: netease
    restart: always
    ports:
      - "8888:8888"
    environment:
      - CAT_BACKEND_PORT=8888
      - CAT_BACKEND_HOST=netease
      - CAT_BACKEND_ALLOWED_ORIGINS=["*"]
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://$$CAT_BACKEND_HOST:$$CAT_BACKEND_PORT/api/healthz || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - netease_network
