services:
  streamlit:
    build:
      context: ../..
      dockerfile: ./docker/streamlit.dockerfile
    container_name: streamlit
    restart: always
    ports:
      - "8501:8501"
    environment:
      - UI_BACKEND_URL=http://netease:8888
    networks:
      - netease_network
