services:
  streamlit:
    build:
      context: ../..
      dockerfile: ./docker/streamlit.dockerfile
    container_name: streamlit
    restart: always
    ports:
      - "8501:8501"
    environment:
      - UI_BACKEND_URL=http://netease:8888
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://streamlit:8501/api/healthz || exit 1"]
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - netease_network
